version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /GATKSVPipelineClinicalTest.wdl
     publish: false
     filters:  # Only develop branch and all tags
         branches:
           - develop
         tags:
           - /.*/
