version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /GATKSVPipelineClinicalTest.wdl
     publish: true
     filters:  # Only main branch and all tags
         branches:
           - main
         tags:
           - /.*/
